#Esse playbook permite abrir um determinado site através do Google-Chrome no windows
- name: Open a website
  hosts: all
  
  tasks:
    - name: selecionando o diretorio do chrome 
      win_shell: start chrome.exe "www.uol.com.br"

