# Esse playbook cira uma nova pasta o host Windows
- name: Criando uma nova pasta 
  hosts: all 

  tasks:
    - name: Criando uma nova pasta
      win_shell: mkdir C:\Users\Administrador\Desktop\"nova pasta"
