# Esse playbook cira uma nova pasta o host Windows
- name: Criando uma nova pasta 
  hosts: all 

  tasks:
    - name: Criando uma nova pasta
      win_shell: cd C:\Users\Administrador\Desktop\
      win_shell: mkdir "nova pasta"
